nelmio_api_doc:
    use_validation_groups: true
    documentation:
        info:
            title: Filme Verwaltung
            description: Endpoints zum Verwaltung von Filmen
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!docs$)